### ISSUE TITLE
AppImage does not run

### ISSUE THREAD

**Issue by probonopd** [ramonreschke/clipboard-to-qrcode#1]
![](https://raw.githubusercontent.com/AppImage/appimage.github.io/d6b72d3f62de5285861069105e575ffc9660bb2f/database/Clipboard_to_QR-Code/screenshot.png)

Reference:
https://github.com/AppImage/appimage.github.io/pull/1107

**Comment by ramonreschke** [comment]
@probonopd Hopefully v0.3.2 will fix it for you! But this app definitely needs some improvements for Linux. I will get to this later!

**Comment by probonopd** [comment]
Thanks @ramonreschke. Now running into

```
Error: Error: net::ERR_INTERNET_DISCONNECTED
    at CancellationToken.createPromise (/run/firejail/appimage/.appimage-10249/resources/app.asar/node_modules/builder-util-runtime/src/CancellationToken.ts:51:12)
    at ElectronHttpExecutor.doApiRequest (/run/firejail/appimage/.appimage-10249/resources/app.asar/node_modules/builder-util-runtime/src/httpExecutor.ts:84:30)
    at ElectronHttpExecutor.request (/run/firejail/appimage/.appimage-10249/resources/app.asar/node_modules/builder-util-runtime/src/httpExecutor.ts:74:17)
    at GitHubProvider.httpRequest (/run/firejail/appimage/.appimage-10249/resources/app.asar/node_modules/electron-updater/src/providers/Provider.ts:29:26)
    at /run/firejail/appimage/.appimage-10249/resources/app.asar/node_modules/electron-updater/src/providers/GitHubProvider.ts:38:41
    at Generator.next (<anonymous>)
From previous event:
    at GitHubProvider.getLatestVersion (/run/firejail/appimage/.appimage-10249/resources/app.asar/node_modules/electron-updater/src/providers/GitHubProvider.ts:35:25)
    at /run/firejail/appimage/.appimage-10249/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:345:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at AppImageUpdater.getUpdateInfo (/run/firejail/appimage/.appimage-10249/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:335:32)
    at /run/firejail/appimage/.appimage-10249/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:349:35
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.doCheckForUpdates (/run/firejail/appimage/.appimage-10249/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:348:34)
    at /run/firejail/appimage/.appimage-10249/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:287:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at AppImageUpdater._checkForUpdates (/run/firejail/appimage/.appimage-10249/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:282:33)
    at AppImageUpdater.checkForUpdates (/run/firejail/appimage/.appimage-10249/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:221:35)
    at App.<anonymous> (/run/firejail/appimage/.appimage-10249/resources/app.asar/main.js:131:17)
    at emitTwo (events.js:131:20)
    at App.emit (events.js:214:7)
```

Luckily, the fix seems to be easy: https://github.com/clipr/clipr/commit/eb82c638de7889f7a5ae911497f14c62cc467ee5 or https://github.com/standardnotes/desktop/commit/d8f71ba6b58ba5c4d4d2db42d04e895880f448e8

References:
* https://github.com/standardnotes/desktop/issues/168
* https://github.com/clipr/clipr/issues/1

I wonder why this can't be fixed for all time in electron-updater though... https://github.com/electron-userland/electron-builder/search?q=ERR_INTERNET_DISCONNECTED&type=Issues
